ban:
- 寻森小鹿男
- 禅心云外镜

team_m:
- name:  封阳君
  yuhun: 
- name:  不知火
  yuhun: 
- name:  祸津神
  yuhun: 
- name:  
  yuhun: 
- name:  
  yuhun: 

team_d:
- name:  祸津神
  yuhun: 
- name:  不知火
  yuhun: 
- name:  
  yuhun: 
- name:  
  yuhun: 
- name:  
  yuhun: 