ban:
- 

team_m:
- name:  夜溟彼岸花
  yuhun: 
- name:  封阳君
  yuhun: 
- name:  一目连
  yuhun: 
- name:  祸津神
  yuhun: 
- name:  心友犬神
  yuhun: 

team_d:
- name:  
  yuhun: 
- name:  
  yuhun: 
- name:  
  yuhun: 
- name:  
  yuhun: 
- name:  
  yuhun: 

start_time: '2024-12-02'
end_time: '2024-12-08'